// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...slug]').default>>>>
    }
    '/api/hello/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello/[...]').default>>>>
    }
    '/api/hello/**:name': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello/[...name]').default>>>>
    }
    '/api/hello/**:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello/[...slug]').default>>>>
    }
    '/api/hello/:name': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello/[name]').default>>>>
    }
    '/api/hello/:name/:age': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hello/[name]/[age]').default>>>>
    }
    '/api/post/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/post/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/post/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/post/[id].put').default>>>>
    }
    '/api/posts': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/posts.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}